name: NodeJS CI-CD

on:
  push:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: |
          echo "Running Tests..." > test-results.txt
          npm test >> test-results.txt 2>&1 || true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.txt


  deploy:
    needs: test

    runs-on: self-hosted

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: test-results

      - name: Display Test Results
        run: |
          echo "===== TEST RESULTS ====="
          cat test-results.txt

      - name: Install Dependencies
        run: npm install

      - name: Deploy Application
        run: |
          sudo apt update
          sudo apt install nginx -y

          sudo rm -rf /var/www/html/*

          sudo cp -r ./* /var/www/html/

          sudo systemctl restart nginx

      - name: Verify Deployment
        run: |
          pm2 list
